### ISSUE TITLE
game/Submods/mas-saysomething-1.7.0/mod/screen.rpy", line 851: u'released' is not a keyword argument or valid child for the bar statement

### ISSUE THREAD

**Issue by Remnitsuu** [Friends-of-Monika/mas-saysomething#13]
" is:issue is:open [code] I'm sorry, but errors were detected in your script. Please correct the errors listed below, and try again.   File "game/Submods/mas-saysomething-1.7.0/mod/screen.rpy", line 851: u'released' is not a keyword argument or valid child for the bar statement.
released Return(_fom_saysomething.RETURN_RENDER)             ^  Ren'Py Version: Ren'Py 6.99.12.4.2187 [/code]"

**Comment by dreamscached** [comment]
You have downloaded the submod using source code, don't do that. Remove `game/Submods/mas-saysomething-1.7.0` folder entirely and install again, following the [instructions](https://github.com/Friends-of-Monika/mas-saysomething#-installing).

**Comment by Remnitsuu** [comment]
thx
