### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by lenvxdev** [Friends-of-Monika/mas-saysomething#2]
[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/mas-saysomething-master/mod/screen.rpy", line 688: u'released' is not a keyword argument or valid child for the bar statement.
    released Return(_fom_saysomething.RETURN_RENDER)
            ^

Ren'Py Version: Ren'Py 6.99.12.4.2187
[/code]

**Comment by dreamscached** [comment]
Do not use source code for installing submods. Source code is designed to work on Ren'Py 8 and Python 3 while [the release version](https://github.com/Friends-of-Monika/mas-saysomething/releases/tag/latest) works under Ren'Py 6 and Python 2.

Delete everything under `game/mod` and use latest release instead.

**Comment by lenvxdev** [comment]
have fixed it
