### ISSUE TITLE
Major issue with Speech Mode

### ISSUE THREAD

**Issue by Dsfan2** [Friends-of-Monika/mas-saysomething#28]
Happens when trying to add a new line.
![Screenshot 2023-07-16 221517](https://github.com/Friends-of-Monika/mas-saysomething/assets/82821066/9393ef3f-2cf7-4de4-8fba-f0704285d966)

**Comment by dreamscached** [comment]
Resolved in 1.8.1, download a new release. Thank you for reporting!
