### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mayeofor** [Friends-of-Monika/mas-saysomething#29]
Hi! im new to this submonds thing and I assume this directory is where I should put the mod. But when I start the game it says this:

[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/submods/mas-saysomething-master/mod/generation.rpy", line 27: unexpected indent
            illegal_chars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*']
            ^
    

File "game/submods/mas-saysomething-master/mod/screen.rpy", line 1121: u'released' is not a keyword argument or valid child for the bar statement.
    released Return(_fom_saysomething.RETURN_RENDER)
            ^

File "game/submods/mas-saysomething-master/mod/screen.rpy", line 203: invalid syntax
                raise ValueError(f"Unknown code in sprite_code: {sprite_code}")
                                                                              ^
    

Ren'Py Version: Ren'Py 6.99.12.4.2187
[/code]

Thank you in advance!

**Comment by dreamscached** [comment]
Hi, unsure if you solved it yourself already — you installed the wrong version of the submod, you downloaded the source code and not the release version. Go [here](https://github.com/friends-of-monika/releases/latest) and download it from there.
