### ISSUE TITLE
Fix vanilla UI

### ISSUE THREAD

**Issue by dreamscached** [Friends-of-Monika/mas-saysomething#30]
I have no idea how I overlooked it and no one beside @yun-seo1 ever told me about it, but the UI layout is off on the official theme (unaffected by ComfyUI). This must be resolved in the next update.

**Comment by RZed01** [comment]
> I have no idea how I overlooked it and no one beside @Yun-Seo1 ever told me about it, but the UI layout is off on the official theme (unaffected by ComfyUI). This must be resolved in the next update.

This bug does happen in the Comfy UI if you are using the Mint theme.

**Comment by RZed01** [comment]
Evidence for that is shown here:
![image](https://github.com/Friends-of-Monika/mas-saysomething/assets/149847536/4df3bb24-f517-4a84-8967-3a0f469c142f)

**Comment by RZed01** [comment]
It may also potentially happen on any theme that uses the font that Mint uses (Default, Cold, Peach, Starry, and Strawberry). I confirmed that the Cold theme also suffers this issue.

**Comment by RZed01** [comment]
It looks correct on themes that use the font featured in the screenshots (Chocolate, Mystique, and Classic)
